from typing import Protocol

class TLSChecker(Protocol):
    def ensure_logged_in(self) -> None: ...
    def has_no_slots(self) -> bool: ...
    def refresh(self) -> None: ...
    def close(self) -> None: ...
