from typing import Protocol, Iterable

class SubscriberStore(Protocol):
    def add(self, chat_id: int) -> bool: ...
    def remove(self, chat_id: int) -> bool: ...
    def all(self) -> Iterable[int]: ...
    def count(self) -> int: ...
    def exists(self, chat_id: int) -> bool: ...
