name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Lint (ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            cache: pip
      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Ruff check
        run: ruff check . --output-format=github

  test:
    name: Tests & Coverage (>=90%)
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Run tests with coverage
        run: |
          pytest -q \
            --cov=. \
            --cov-report=term-missing:skip-covered \
            --cov-report=xml:coverage.xml \
            --cov-report=html:htmlcov \
            --cov-fail-under=90
      - name: Coverage summary
        if: matrix.python-version == '3.12'
        run: |
          python -c "import xml.etree.ElementTree as ET; r=ET.parse('coverage.xml').getroot(); print(f'Total line coverage: {float(r.get(\"line-rate\",\"0\"))*100:.2f}%')"
      - name: Upload coverage HTML (single py version)
        if: matrix.python-version == '3.12' && (success() || failure())
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
      - name: Upload coverage XML (single py version)
        if: matrix.python-version == '3.12' && (success() || failure())
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
